<?= Cargar::parcial('encabezado') ?>
<main>    
    <h1>SimpleMVC les da la bienvenida</h1>
    <?= Cargar::parcial('flash') ?>
    <article>
        <p>Muchas gracias por confiar en este proyecto. La idea principal es contar con las bondades de un framework MVC, con terminología en español y un grupo de librerías básicas para realizar proyectos.</p>
        <p>
        <strong>SimpleMVC</strong> puede usarse tanto en aplicaciones web estáticas como en aquellas que requieren bases de datos.</p>
        <p>
        Actualmente el proyecto está usando la librería <a href="http://simplecss.org/" target="_blank">SimpleCss</a> para el aspecto visual.
        </p>
        <p>
        En términos de acceso a bases de datos utiliza una clase basada en el estándar <a href="https://www.php.net/manual/es/book.pdo.php" target="_blank">PDO (PHP Data Objects)</a> por lo que podrás utilizar cualquier motor de base de datos que tenga soporte para PDO, por ejemplo MySQL, Postgres, Sqlite, entre otros.
        </p>
    </article>
    <br>
    <article>
        <p>La documentación puede revisarse en la sección <a href="https://github.com/nelsonrojasn/SimpleMVC/wiki" target="_blank">Wiki</a> dentro del repositorio de Github</p>
    </article>
</main>

<?= Cargar::parcial('piedepagina') ?>

