<!doctype html>
<html>
    <head>
        <title>IsaliaPHP les da la bienvenida</title>
        <link rel="stylesheet" type="text/css" 
              href="<?= PUBLIC_PATH ?>css/pico.css">              
        <link rel="stylesheet" type="text/css" 
              href="<?= PUBLIC_PATH ?>css/alerts.css">              
    </head>
    <body class="container">
    	<?php echo View::getContent(); ?>    	
  	<?php echo View::partial('footer'); ?>
    </body>
</html>
    
