<!doctype html>
<html>
    <head>
        <title>IsaliaPHP les da la bienvenida</title>
        <link rel="stylesheet" type="text/css" 
              href="<?= PUBLIC_PATH ?>css/simple.css">
              <link rel="stylesheet" type="text/css" 
              href="<?= PUBLIC_PATH ?>css/custom.css">
    </head>
    <body>
    	<?php echo View::getContent(); ?>    	
  	<?php echo View::partial('footer'); ?>
    </body>
</html>
    
