<header>
    <h1><span class="text-primary">IsaliaPHP</span> les da la bienvenida</h1>
</header>

<?php if (Flash::hasMessages()): ?>    
    <?= Flash::render(); ?>
<?php endif; ?>

<main>
    <article class="well">
        <p>Muchas gracias por confiar en este proyecto. La idea principal es contar con las bondades de un framework MVC, con documentación en español y un grupo de librerías básicas para realizar proyectos.</p>
        <p>
            <strong>IsaliaPHP</strong> puede usarse tanto en aplicaciones web estáticas como en aquellas que requieren bases de datos.
        </p>
        <p>
            En términos de acceso a bases de datos incluye una clase para ORM y otra clase para enviar SQL directo, ambas basadas en el estándar <a href="https://www.php.net/manual/es/book.pdo.php" target="_blank">PDO (PHP Data Objects)</a> por lo que podrás utilizar cualquier motor de base de datos que tenga soporte para PDO, por ejemplo MySQL, Postgres, Sqlite, entre otros.
        </p>
    </article>
    <br>
    <article>
        <p>La documentación puede revisarse desde <a href="https://isaliaphp.github.io/IsaliaPHP/" target="_blank">https://isaliaphp.github.io/IsaliaPHP/</a></p>
    </article>
</main>