<?= Cargar::parcial('encabezado') ?>
<h1>Agregar usuario</h1>

<form action="" method="post">
    <label>Email</label>
    <input type="text" name="usuario[email]" id="usuario_email" /><br>
    <label>Nombre</label>
    <input type="text" name="usuario[nombre]" id="usuario_nombre" /><br>
    <label>Clave</label>
    <input type="password" name="usuario[clave]" id="usuario_clave" /><br>
    <label>Activo</label>
    <input type="text" name="usuario[activo]" id="usuario_activo" /><br>
    
    <input type="submit" value="Enviar" />
</form>

<?= Cargar::parcial('piedepagina') ?>

