<?= Cargar::parcial('encabezado') ?>
<h1>Editar usuario</h1>

<form action="" method="post">
    <label>Email</label>
    <input type="text" name="usuario[email]" 
           id="usuario_email" value="<?= $usuario['email'] ?>"/><br>
    <label>Nombre</label>
    <input type="text" name="usuario[nombre]" 
           id="usuario_nombre" value="<?= $usuario['nombre'] ?>" /><br>
    <label>Activo</label>
    <input type="text" name="usuario[activo]" 
           id="usuario_activo" value="<?= $usuario['activo'] ?>" /><br>
    
    <input type="submit" value="Actualizar" />
</form>

<?= Cargar::parcial('piedepagina') ?>

