<?= Cargar::parcial('encabezado') ?>
<h3>Lista de usuarios</h3>
<a href="<?=RUTA_PUBLICA?>usuarios/agregar">Agregar nuevo usuario</a>
<ul>
<?php foreach ($usuarios as $u): ?>
    <li>
        <?=$u['nombre']?> <a href="<?=RUTA_PUBLICA?>usuarios/editar/<?=$u['id']?>">Editar</a>
        &nbsp;<a href="<?=RUTA_PUBLICA?>usuarios/eliminar/<?=$u['id']?>">Eliminar</a>
    </li>
<?php endforeach; ?>    
</ul>
<?= Cargar::parcial('piedepagina') ?>

