<h1>Create New Post</h1>

<?php if (Flash::hasMessages()) { ?>    
    <?= Flash::render(); ?>
<?php } ?>


<form action="<?= PUBLIC_PATH ?>posts/create" method="post">
    <div>
        <label for="post_title">Title:</label>
        <input type="text" id="post_title" name="post[title]" required>
    </div>
    
    <div>
        <label for="post_body">Body:</label>
        <textarea id="post_body" name="post[body]" required></textarea>
    </div>
    
    <div>
        <button type="submit">Create Post</button>
    </div>
</form>


<?= Html::link('posts', 'Back to Posts') ?>
