<h1>Create New Post</h1>

<?php if (Flash::hasMessages()): ?>    
    <?= Flash::render(); ?>
<?php endif; ?>


<?= Form::open("posts/create")?>
    <div>
        <?= Form::label("post.title", "Title:"); ?>
        <?= Form::text("post.title", 'required') ?>
    </div>
    
    <div>
        <?= Form::label("post.body", "Body:"); ?>
        <?= Form::textarea("post.body", 'required') ?>
    </div>
    
    <div style="margin-top: 1em;">
        <?= Form::submit("Create Post") ?>
        <?= Html::link('posts', 'Back to Posts') ?>
    </div>
<?= Form::close(); ?>