<h1>Crear nueva publicación</h1>

<?php if (Flash::hasMessages()): ?>    
    <?= Flash::render(); ?>
<?php endif; ?>


<?= Form::open("posts/create")?>
    <div>
        <?= Form::label("post.title", "Título:"); ?>
        <?= Form::text("post.title", 'required') ?>
    </div>
    
    <div>
        <?= Form::label("post.body", "Cuerpo:"); ?>
        <?= Form::textarea("post.body", 'required') ?>
    </div>
    
    <div style="margin-top: 1em;">
        <?= Form::submit("Crear") ?>
        <?= Html::link('posts', 'Volver a publicaciones') ?>
    </div>
<?= Form::close(); ?>