<h1>Edit Post</h1>

<?php if (Flash::hasMessages()): ?>    
    <?= Flash::render(); ?>
<?php endif; ?>


<?= Form::open("posts/edit/". $post->id)?>

    <div>
        <?= Form::label("post.title", "Title:"); ?>
        <?= Form::text("post.title", 'required', htmlspecialchars($post->title)); ?>        
    </div>
    
    <div>
        <?= Form::label("post.body", "Body:"); ?>
        <?= Form::textarea("post.body", 'required', htmlspecialchars($post->body)); ?>        
    </div>
    
    <div style="margin-top: 1em;">
        <?= Form::submit("Update Post"); ?>
        <?= Html::link('posts', 'Back to Posts') ?>
        <?= Html::link("posts/view/{$post->id}", 'View Post') ?>
    </div>
<?= Form::close(); ?>

