<h1>Editar publicación</h1>

<?php if (Flash::hasMessages()): ?>    
    <?= Flash::render(); ?>
<?php endif; ?>


<?= Form::open("posts/edit/". $post->id)?>

    <div>
        <?= Form::label("post.title", "Título:"); ?>
        <?= Form::text("post.title", 'required', htmlspecialchars($post->title)); ?>        
    </div>
    
    <div>
        <?= Form::label("post.body", "Cuerpo:"); ?>
        <?= Form::textarea("post.body", 'required', htmlspecialchars($post->body)); ?>        
    </div>
    
    <div style="margin-top: 1em;">
        <?= Form::submit("Actualizar publicación"); ?>
        <?= Html::link('posts', 'Volver a publicaciones') ?>
        <?= Html::link("posts/view/{$post->id}", 'Ver publicación') ?>
    </div>
<?= Form::close(); ?>

