<h1>Lista de publicaciones</h1>

<?php if (Flash::hasMessages()): ?>    
    <?= Flash::render(); ?>
<?php endif; ?>

<?= Html::link("posts/create", "Crear una publicación") ?>
<table style="margin-top: 1em;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Cuerpo</th>
            <th>Fecha Creación</th>
            <th>Fecha Actualización</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($posts as $post): ?>
            <tr>
                <td><?= $post->id; ?></td>
                <td><?= $post->title; ?></td>
                <td><?= substr($post->body, 0, 100) . '...'; ?></td>
                <td><?= $post->created_at; ?></td>
                <td><?= $post->updated_at; ?></td>
                <td>
                    <?= Html::link("posts/show/$post->id", "Ver") ?>
                    <?= Html::link("posts/edit/$post->id", "Editar") ?>
                    <?= Html::link("posts/delete/$post->id", "Eliminar", ["onclick" => "return confirm('Está seguro/a?')"]) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
